### ISSUE TITLE
Version >1.0.1 not working for me

### ISSUE THREAD

**Issue by rodehutokus** [Yoshify/DiscJockey#13]
Only mod version 1.0.0 and 1.0.1 working for me, for the other versions custom songs are not showing in the UI at all and after a song was downloaded via Youtube link it cannot be played, here is the error code:

[Error  : Unity Log] TypeLoadException: Could not resolve type with token 0100001a from typeref (expected class 'System.IO.Stream' in assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a')
Stack trace:
(wrapper remoting-invoke-with-check) NAudio.Wave.AudioFileReader..ctor(string)
DiscJockey.Audio.CachedAudio.FromFilePath (System.String fileName, System.String name) (at <5105695db27a43dca62599d530b24f3f>:0)
DiscJockey.Audio.AudioLoader.LoadAudioFromDisk (System.String filePath, System.String clipNameOverride) (at <5105695db27a43dca62599d530b24f3f>:0)
DiscJockey.Audio.AudioLoader.LoadAudioClipsFromDirectory (System.String directory) (at <5105695db27a43dca62599d530b24f3f>:0)
System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__7_0 (System.Object state) (at <787acc3c9a4c471ba7d971300105af24>:0)
UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <e27997765c1848b09d8073e5d642717a>:0)
UnityEngine.UnitySynchronizationContext.Exec () (at <e27997765c1848b09d8073e5d642717a>:0)
UnityEngine.UnitySynchronizationContext.ExecuteTasks () (at <e27997765c1848b09d8073e5d642717a>:0)

**Comment by rodehutokus** [comment]
Now tried installation with r2modman which fixed the issue

**Comment by rodehutokus** [comment]
Ok I finally found out what caused the issue in the first place: I was also using the mod "Radio Furniture" from Bobby and this was also using NAudio and Unitask as dependencies. After removing Bobbys mods NAudio and UniTask from my modlist DiscJockey was again working for me aswell as the Radio Furniture mod.

**Comment by Yoshify** [comment]
That's... bizarre. Thank you for flagging that with me. No idea why that would happen.
