### ISSUE TITLE
Mod pulled from Thunderstore?

### ISSUE THREAD

**Issue by welles** [Yoshify/DiscJockey#19]
Hi, I just realized your mod is missing from Thunderstore. Was this on purpose?
My friends and I have been enjoying it very much, would be very sad if development stopped.

**Comment by Yoshify** [comment]
Thanks for letting me know, development is alive and well!
I've reached out to a Thunderstore admin and had the listing reinstated - neither of us are sure why it was pulled in the first place, but it's back now. Must have been a bug.
