### ISSUE TITLE
I'm blue dabadi dabadie

### ISSUE THREAD

**Issue by VanilaBOI** [Yoshify/DiscJockey#5]
When I play this song it never finishes loading and also the F10 open interface tooltip is douplicated

**Comment by VanilaBOI** [comment]
https://www.youtube.com/watch?v=68ugkg9RePc

**Comment by VanilaBOI** [comment]
Nevermind now nothing works
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object.
Stack trace:
DiscJockey.Managers.DiscJockeyUIManager+<>c__DisplayClass31_0.<FindMatchingTrackListButton>b__0 (DiscJockey.Data.TrackListButton tlb) (at <ba980c91196b445a9e0c82ca1ebf2eb2>:IL_0006)
System.Linq.Enumerable.TryGetFirst[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate, System.Boolean& found) (at <dab7f68612224ba3ae40f651d44f9d4c>:IL_003F)
System.Linq.Enumerable.FirstOrDefault[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] predicate) (at <dab7f68612224ba3ae40f651d44f9d4c>:IL_0000)
DiscJockey.Managers.DiscJockeyUIManager.FindMatchingTrackListButton (System.Int32 trackIndex) (at <ba980c91196b445a9e0c82ca1ebf2eb2>:IL_000D)
DiscJockey.Managers.DiscJockeyUIManager.OnPlayTrack (BoomboxItem boomboxItem, DiscJockey.Data.BoomboxMetadata boomboxMetadata) (at <ba980c91196b445a9e0c82ca1ebf2eb2>:IL_0037)
DiscJockey.Managers.DiscJockeyNetworkManager.RequestPlayForBoomboxClientRpc (System.UInt64 boomboxId, DiscJockey.Data.BoomboxMetadata metadata) (at <ba980c91196b445a9e0c82ca1ebf2eb2>:IL_0132)
DiscJockey.Managers.DiscJockeyNetworkManager.RequestPlayForBoomboxServerRpc (System.UInt64 boomboxId, DiscJockey.Data.BoomboxMetadata metadata) (at <ba980c91196b445a9e0c82ca1ebf2eb2>:IL_00FA)
DiscJockey.Managers.DiscJockeyNetworkManager.__rpc_handler_1154972047 (Unity.Netcode.NetworkBehaviour target, Unity.Netcode.FastBufferReader reader, Unity.Netcode.__RpcParams rpcParams) (at <ba980c91196b445a9e0c82ca1ebf2eb2>:IL_0056)
Unity.Netcode.RpcMessageHelpers.Handle (Unity.Netcode.NetworkContext& context, Unity.Netcode.RpcMetadata& metadata, Unity.Netcode.FastBufferReader& payload, Unity.Netcode.__RpcParams& rpcParams) (at <1b23ec5fcbfc4fbca0db70afcdb9b715>:IL_004E)
Rethrow as Exception: Unhandled RPC exception!
UnityEngine.Debug:LogException(Exception)
Unity.Netcode.RpcMessageHelpers:Handle(NetworkContext&, RpcMetadata&, FastBufferReader&, __RpcParams&)
Unity.Netcode.ServerRpcMessage:Handle(NetworkContext&)
Unity.Netcode.NetworkBehaviour:__endSendServerRpc(FastBufferWriter&, UInt32, ServerRpcParams, RpcDelivery)
DiscJockey.Managers.DiscJockeyNetworkManager:RequestPlayForBoomboxServerRpc(UInt64, BoomboxMetadata)
DiscJockey.Managers.DiscJockeyAudioManager:RequestPlayTrack(Track)
DiscJockey.Managers.<>c:<InitUIEvents>b__49_2()
UnityEngine.EventSystems.EventSystem:Update()

**Comment by VanilaBOI** [comment]
)I also get this after a restart on startup

[Error  :Yoshify.DiscJockey] DiscJockey 1.0.1: OnLoadAllAudioFromDirectoryError: Found no files to load in C:\Users\Sunny Arnold\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Vanilla Modpack 1.0\BepInEx\plugins\Yoshify-DiscJockey\Custom Songs

[Error  :Yoshify.DiscJockey] DiscJockey 1.0.1: OnLoadAllAudioFromDirectoryError: Found no files to load in C:\Users\Sunny Arnold\AppData\Roaming\Thunderstore Mod Manager\DataFolder\LethalCompany\profiles\Vanilla Modpack 1.0\BepInEx\plugins\Yoshify-DiscJockey\Custom Songs

**Comment by Yoshify** [comment]
All these issues should be fixed in version 1.1.0 - please give it a go!
