### ISSUE TITLE
suggestion: change the name of the mod

### ISSUE THREAD

**Issue by charleypepito1** [Yoshify/DiscJockey#7]
I didn't know where to type this but I was looking everywhere for a YouTube compatible boombox mod and I couldn't find any that worked, yours is perfect and works fine but the name isn't easy to find on the mod manager/launcher and I had to look far and wide to finally find yours, basically what I mean is you should probably add at least the word "Boombox" in the name so it pops up in the search and you get more recognition because this mod is good. "DiscJockey Boombox Mod" maybe? idk just thinking

**Comment by Yoshify** [comment]
Thanks for the suggestion, I've been considering it after also failing to find my own mod in google searches haha.
Not so easy to do once it's on Thunderstore though, unfortunately. Requires basically a full reset. Might reach out to an admin and see what they can do for me.
