### ISSUE TITLE
My friends cant join me when i use this mod

### ISSUE THREAD

**Issue by tendo90** [Yoshify/DiscJockey#9]
Does everyone need to have this mod or should it be enough if i as a host has it?

In unity every time someone tries to join it says :

"Player joined "
[Warning: Unity Log] [Netcode] NetworkConfig mismatch. The configuration between the server and client does not match
[Info   : Unity Log] Disconnect callback called
[Info   : Unity Log] Is server: True; ishost: True; isConnectedClient: True
[Info   : Unity Log] Disconnect callback called in gamenetworkmanager; disconnecting clientId: 1
[Info   : Unity Log] A Player disconnected but they were not in clientplayerlist

**Comment by Yoshify** [comment]
Everyone will need this mod :)
